"""add_new_onboarding_fields

Revision ID: 54f53f2927c2
Revises: c7bbe6aea939
Create Date: 2026-03-19 19:06:50.782171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f53f2927c2'
down_revision: Union[str, None] = 'c7bbe6aea939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_book_sources_book_id', table_name='book_sources')
    op.create_index(op.f('ix_book_sources_book_id'), 'book_sources', ['book_id'], unique=False)
    op.add_column('onboarding_profiles', sa.Column('business_name', sa.String(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('business_age', sa.String(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('business_origin', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('primary_problems', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('root_cause', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('personal_impact', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('secondary_problems', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('why_book_not_random', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('solutions_tried', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('ideal_book_description', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('future_vision', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('consequence_if_unsolved', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('why_now', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('transition_summary', sa.Text(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('transition_confirmed', sa.Boolean(), nullable=True))
    op.add_column('onboarding_profiles', sa.Column('transition_correction', sa.Text(), nullable=True))
    op.drop_index('ix_users_email_lower_unique', table_name='users', postgresql_where='(email IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email_lower_unique', 'users', [sa.text('lower(email::text)')], unique=True, postgresql_where='(email IS NOT NULL)')
    op.drop_column('onboarding_profiles', 'transition_correction')
    op.drop_column('onboarding_profiles', 'transition_confirmed')
    op.drop_column('onboarding_profiles', 'transition_summary')
    op.drop_column('onboarding_profiles', 'why_now')
    op.drop_column('onboarding_profiles', 'consequence_if_unsolved')
    op.drop_column('onboarding_profiles', 'future_vision')
    op.drop_column('onboarding_profiles', 'ideal_book_description')
    op.drop_column('onboarding_profiles', 'solutions_tried')
    op.drop_column('onboarding_profiles', 'why_book_not_random')
    op.drop_column('onboarding_profiles', 'secondary_problems')
    op.drop_column('onboarding_profiles', 'personal_impact')
    op.drop_column('onboarding_profiles', 'root_cause')
    op.drop_column('onboarding_profiles', 'primary_problems')
    op.drop_column('onboarding_profiles', 'business_origin')
    op.drop_column('onboarding_profiles', 'business_age')
    op.drop_column('onboarding_profiles', 'business_name')
    op.drop_index(op.f('ix_book_sources_book_id'), table_name='book_sources')
    op.create_index('idx_book_sources_book_id', 'book_sources', ['book_id'], unique=False)
    # ### end Alembic commands ###

